# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97e5a68783ebff4c8bc8a66b055f0b212ca05172beb8448c70aacab2d5ffb0fb06f0eb57ae117dd65ad3cf86b9d7921d310d1a1978b8c8052759211b1d300b0b

test:
  secret_key_base: 676fbaca80a8f4216f4ea11ab03e0abed53fd51683caff2f57de841e29308991f93178e38458ef77635c29a03cb5de28368e20d82cb8808b5d30d06e8de7c689

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
